### ISSUE TITLE
onERC721Received uses too much gas

### ISSUE THREAD

**Issue by mudgen** [mattlockyer/composables-998#2]
onERC721Received calls the childReceived function which writes 5 words to storage which costs 100,000 gas.  But the [ERC721 standard](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md) requires that the onERC721Received function use no more than 50,000 gas

**Comment by mudgen** [comment]
But it looks like the 50,000 gas limit might be removed from the ERC721 standard: https://github.com/ethereum/EIPs/pull/1125

**Comment by mattlockyer** [comment]
There's currently no way around the extra book keeping in order to also support enumerability for wallets.

Do you know why the standard has an arbitrary limit of 50k?

Do you have any ideas?

I was thinking of making enumerable abstract for erc20 and erc721 so it would be optional.

At the end of the day, a standard can really only go as far as the interface. If a 998 looks like a 721 and has the same signatures it will be usable by wallets, exchanges and applications all the same.

**Comment by mudgen** [comment]
I think the arbitrary limit of 50,000 gas is to prevent contracts from abusing the call into them and perhaps to prevent reentry attacks.

I emailed @fulldecent about getting that limit removed.

**Comment by mudgen** [comment]
The 50,000 gas limit was removed from the ERC721 standard!
